# A sample Gemfile
source "https://rubygems.org"

gem "teacup"
gem "sugarcube"
gem "sweettea"
gem 'bubble-wrap'
gem "motion-awesome"
gem "motion-map"
gem "geomotion"
#gem "motion-xray"
gem "motion-rubberstamp"
group :development do
	gem "awesome_print_motion"
end
