# A sample Gemfile
source "https://rubygems.org"

gem "teacup"
gem "sugarcube", :git => "git://github.com/colinta/sugarcube.git", :branch => "1.0", :require => "sugarcube-common"
gem "sweettea"
gem 'bubble-wrap'
gem "motion-awesome" # now handled by sugarcube-awesome
gem "motion-map"
gem "geomotion"
#gem "motion-xray"
gem "motion-rubberstamp"#, :git => "git@github.com:IconoclastLabs/motion-rubberstamp.git"
group :development do
	gem "awesome_print_motion"
end
